name: Automatically create / update pull request

on:
  push:
    branches:
      - "main"

jobs:
  merge-to-stage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create PR from main to stage
      run: |
        git checkout main
        git pull origin main
        git checkout -b stage
        git push origin stage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Approve PR
      run: |
        PR_URL=$(gh pr create --base stage --head main --title "Merge from main to stage" --body "Automated PR creation")
        gh pr review $PR_URL --approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge PR to stage
      run: |
        PR_URL=$(gh pr list --base stage --state open | grep "Merge from main to stage" | cut -f 1)
        gh pr merge $PR_URL --auto
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
