name: Automatically create / update pull request

on:
  push:
    branches:
      - "main"

jobs:
  merge-to-stage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create PR from main to stage
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "stage"
        pr_title: "Sync main into stage (Auto-created PR)"
        pr_body: "Automated PR creation"
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"

    - name: Approve PR
      run: |
        gh pr review --body "Automated PR creation" --approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


